apiVersion: v1
kind: Service
metadata:
  name: devops-toolkit
  labels:
    app: devops-toolkit
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30008
    name: http
  selector:
    app: devops-toolkit
